name: Deploy Install Script

on:
  push:
    branches:
      - main
    paths:
      - 'docs/public/install.sh'
      - '.github/workflows/deploy-install-script.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create site directory
        run: |
          mkdir -p _site
          cp docs/public/install.sh _site/install.sh
          
          # Create a simple index.html that redirects to the main docs
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Refaktor</title>
            <meta http-equiv="refresh" content="0; url=https://github.com/DocSpring/refaktor">
          </head>
          <body>
            <p>Redirecting to <a href="https://github.com/DocSpring/refaktor">Refaktor GitHub</a>...</p>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4