name: E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  e2e:
    name: Self-Hosting Demo
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install ripgrep
        run: |
          if ! command -v rg &> /dev/null; then
            echo "Installing ripgrep..."
            if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
              sudo apt-get update && sudo apt-get install -y ripgrep
            elif [ "${{ matrix.os }}" == "macos-latest" ]; then
              brew install ripgrep
            else  # windows
              choco install ripgrep
            fi
          fi
        shell: bash

      - name: Run e2e test
        run: |
          ./scripts/e2e-test.sh
