name: MCP Server CI

on:
  push:
    branches: [main]
    paths:
      - "renamify-mcp/**"
      - ".github/workflows/mcp.yml"
  pull_request:
    branches: [main]
    paths:
      - "renamify-mcp/**"
      - ".github/workflows/mcp.yml"

jobs:
  mcp_test:
    name: Test MCP Server
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('renamify-mcp/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: cd renamify-mcp && pnpm install

      - name: Run TypeScript checks
        run: cd renamify-mcp && pnpm exec tsc --noEmit

      - name: Run Biome checks
        run: cd renamify-mcp && pnpm run check

      - name: Run tests with coverage
        run: cd renamify-mcp && pnpm exec vitest run --coverage

      - name: Build
        run: cd renamify-mcp && pnpm run build
